server:
  port: 8002

#mybatis配置
mybatis:
  type-aliases-package: com.wang.springcloud.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml

#Spring的配置
spring:
  application:
    name: springcloud-provider-dept   #三个服务名称一致是前提!
  #数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db02?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

#Eureka配置, 配置该服务注册到哪里(与Server中的url地址一致)
eureka:
  client:
    service-url:
      #向集群发布, 只需要向所有的Eureka发布url就可以了
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept8002  #修改Eureka上的默认描述信息

#监控信息配置 info
info:
  app.name: wang-springcloud
  company.name: wang.study.com